### ISSUE TITLE
WET 3.1 style guide

### ISSUE THREAD

**Issue by thomasgohard** [wet-boew/wet-boew-styleguide#220]
Where should the WET 3.1 style guide be archived?

Now that WET 3.1 is no longer supported, the WET 3.1 style guide no longer belongs in this repository.

**Comment by thekodester** [comment]
Closing as fixed by https://github.com/wet-boew/wet-boew-styleguide/issues/363 and https://github.com/wet-boew/wet-boew-styleguide/pull/364.
