### ISSUE TITLE
Details/Summary Polyfill widget not perceived as clickable

### ISSUE THREAD

**Issue by neoinsight** [wet-boew/wet-boew-styleguide#222]
Recent usability tests of this widget on a CIC page confirmed something we had seen in mobile participants in the June testing. People overlook these detail/summary items and use other actionable page objects because the expand/collapse items do not appear to be actionable. In fact, in this round of testing, one of the participants slides her cursor over them in frustration and says "These aren't links". Participants are unable to solve the task correctly, because they simply do not click to expand the item with the answer in it. 

The expand/collapse widget is shown in the video clip below in two forms. In the first segment of the clip, we see the widget with a button outline.  Ron at Transport modified it for the prototype testing, as we had previous usability test data on this widget that showed that people did not perceive it as a link. This was a successful approach - no one missed it.   In the second and third segments, you see the widget NOT being clicked,in fact the user says out loud that it is not a link. Several people failed to click that widget. Instead they used the map, which was not correct.  We believe that the current arrows look like bullets when used in a list,  instead of actions.
http://www.screencast.com/t/BSY9haLnG

Potential solutions: 
** A quick fix would be to add underlining, so that at least people can tell it's clickable. Other ideas in image below. 

Ron added button highlighting, that worked very well but will look too complex in a list like the one on the Visa page. I believe in our heuristics review, we pointed out that the side arrow is not a good indicator that content is hidden below, and in fact, is directly inconsistent with the downward-facing chevron on the menus that show content is available below. The convention is a down-facing arrow.  Even placing the arrow at the END of the line would have helped.

And the style guide should suggest that the most important content on a page should NOT be collapsed when the user first views the page... 

Or if this widget has an option to default a particular item to Expanded, that would really help too. 

@pjackson28 - wasn't sure if this was the right place to file this issue or not...
![details polyfill ideas](https://cloud.githubusercontent.com/assets/1855584/4510479/d057e83e-4b2a-11e4-9db4-dfa6e190168f.png)

**Comment by neoinsight** [comment]
@pjackson28 Can you explain about headings in the details/summary? Because we've just done more testing of Canada.ca pages, and once again, most people did not use the element, said later they hadn't noticed it (because they were looking for something to click) and another participant mentioned "well it didn't look like something I could click - it wasn't highlighted". Are you saying I could mark it up as a header and that could give it underlining, etc. to make it look clickable?

**Comment by pjackson28** [comment]
@goodnight Yes, you can now use heading markup in the summary element and could style it with CSS to make it look more clickable. We should be careful about applying global styles though since details/summary are used in the mobile panel, in the toggle accordion and for the tabbed interface (particularly in mobile view). Would be good to identify in what cases the styling should change so we can target it at just those cases to avoid breaking other uses.

**Comment by DK-TBS** [comment]
Agreed, Mr @pjackson28.  No need to add underlining to the component when it's used in the mobile nav panel, users seem to understand it just fine in that context.

But pretty much any time the details/summary thing is employed in the content area of a page, we should get the underline in to help users recognize it.  This would include cases where it's working as a toggle accordion, or when it's pinch-hitting for a tabbed interface.

Should I open a new issue in the GCWeb repo for this?  Would be good to get it in the works...

**Comment by pjackson28** [comment]
@DK-TBS I would caution against applying underlining to the tabbed interface in mobile view, that will end up being a lot of lines since the details/summary are already each encased in a box (which would mean three horizontal lines in close proximity). Different for the regular accordion (in the Toggle example) and the normal details/summary which don't have the box.

So it is important that we be very specific about where the underlining should and shouldn't be so we can target the specific cases where it is needed and not negatively impact the cases where it is not. For the toggle accordion, should we make it more like the tabbed interface in mobile view (with the boxes) rather than using underlining? Traditionally accordions are in boxes, and I've very rarely seen them underlined.

As for the issue, it should be filed to wet-boew/wet-boew since it is a core issue and not specific to any theme.

**Comment by neoinsight** [comment]
@DK-TBS @pjackson28 I am running mobile and desktop participants next week on the test form, and for that test, I have underlined the details/summary item on the first page of the form. You can see it here: http://thomasgohard.github.io/web-form-validation-test/index-en.html  

I'm not up to finessing any of the code to make the underlining not appear in mobile view - and am only using the normal details/summary component. The mobile participants are all planned for Saturday March 14th, so if there is a chance to change it before then, you could fork it - @thomasgohard 

Agree that traditional accordions are in boxes, but I've not seen any gc WET4 page use them that way. They are all just showing one or a set of details summary components. 

For usability testing purposes for next week, It would be easy to split the details summary  element I've implemented into 3 or 4 different ones, might actually be a better test since the effect is even worse on a desktop in a list, since people seem to just think they are a list.

**Comment by pjackson28** [comment]
If you are looking for examples with the boxes, then see the tabbed interface working examples in mobile view (so less than 992px width). http://wet-boew.github.io/v4.0-ci/demos/tabs/tabs-en.html. That looks much more like a traditional accordion than the Toggle accordion does.

If the tabbed interface boxed approach works, then perhaps a solution for the toggle accordion would be to provide a class for adding or removing the boxes (depending on if the default should be with boxes on or off). It would be good to have those two approaches to be consistent (since an accordion is an accordion).

As for regular details/summary, are there cases where a boxed approach would be good? If so, then maybe we could have a class for adding the boxes like with the accordion. The benefit of having an optional class is it avoid dangerous global styles than could cause issues in existing implementations. Of course with an optional class you would have to be very clear about when it should be used.

**Comment by DK-TBS** [comment]
Hmm, I see your point about the boxes, @pjackson28... they definitely do seem to help a lot, and adding underlines probably will clutter things up visually in there.

Hey Lisa @neoinsight, what do you think?  I've seen you point to a number of problematic examples of the details/summary component, but I don't think any of them were presented in boxes.  When tabbed interfaces are rendered in mobile view, the tabs are switched to present like the details/summary component, but they are displayed in boxes.  This seems like it might help users understand that the element is clickable.

You'll see this in action on the example page that Paul linked to.  In these cases, do you think the white boxes are enough to get us past the problem, or do you think they'd still benefit from underlines?  I suppose some user testing is probably the best way to find out, isn't it...

**Comment by neoinsight** [comment]
Just looked at the tabbed example. Agree that an accordion is an accordion, even if it is used by itself. And yes, I think the boxes may help, although am worried people are focused on looking for linked words. 
Let's try it in the @thomasgohard test form, instead of the underlining that I added.  Or what I would really like to do is compare. So if someone can add a copy of the current details/summary in the form so that it uses a box, then I can go in on the weekend and add one on another page to create a comparison.

**Comment by neoinsight** [comment]
Here is what we are testing  http://thomasgohard.github.io/web-form-validation-test/index-en.html @thomasgohard and I implemented it last night. 
There are two details/summary components in a row for the last question. One has a box, one is underlined. 
@pjackson28 I assume this is what you meant about a boxed approach? 

@pcwsmith The experimental design is to see whether people skip past the box and use the underlined words. Not perfect but I couldn't come up with another design in such a short time that had similar 'high demand' for them to open the details/summary.

**Comment by pjackson28** [comment]
@neoinsight I was meaning the accordion-style boxes used by the tabbed interface mobile view (see attached image)
![accordion](https://cloud.githubusercontent.com/assets/1326498/6555877/c10c5ad2-c63f-11e4-8fd6-49acca3c39f4.jpg)

The "boxed" example you are using for testing seems to be a "collapsible alert".

**Comment by neoinsight** [comment]
@pjackson28 Yes, it is a collapsible alert, as mentioned, I had to start with something easy to implement. The other thing is that much of the time, the details/summary is only used in situations where there is only one of them,not a list. 
But if @LaurentGoderre could change the custom CSS that @thomasgohard created late last night to make it look more like your example above, that would be great.

**Comment by nrustand92** [comment]
@neoinsight @pjackson28 @thomasgohard @LaurentGoderre any opinion on +/- rather than arrow? I feel like something like this has been suggested in the past, just can't seem to find the issue.
![expandcollapse](https://cloud.githubusercontent.com/assets/5949078/6948545/937cb7b6-d87c-11e4-8120-1426a8d3f76b.png)

**Comment by LaurentGoderre** [comment]
I was wondering the same today

**Comment by pjackson28** [comment]
@neoinsight The issue is that HTML5 and the native browser support use the arrow and not +/-. If we want to make such a change, then it should be addressed with HTML5 and the browsers and not just by us forcing complicated overrides to the native support in browsers.

**Comment by neoinsight** [comment]
@nrustand92 While that might help reduce the perception of the arrow as a 'bullet', I don't think it would help with overall 'clickability' as people scan. Because it doesn't look actionable, they don't even read it. It needs to look more like a button or link.

**Comment by nrustand92** [comment]
@pjackson28  thanks for the insight

@neoinsight I just need a bit of clarification b/c I recall you mentioning it looking like a button in the meeting earlier today.  If the arrow/plus/minus sign (whatever the icon is) looks like a button + you underline the sentence so it looks like a link, that would be a potentially good solution?  Just double-checking to see if I understand you correctly, thanks.

**Comment by nrustand92** [comment]
Something like this (box around the icon: my attempt to make it look like a button, but I'm sure there's a better way to present that):

![expandcollapsebuttonlink](https://cloud.githubusercontent.com/assets/5949078/6952521/804e6478-d890-11e4-90c7-8ae0b13812a5.png)

**Comment by thomasgohard** [comment]
@nrustand92 I think it would be best to make the entire summary element look like a button. When just making the arrow part look like a button it looks like a "play" button.

**Comment by nrustand92** [comment]
@thomasgohard got it.  Yeah, that was just a quick and dirty mockup.

**Comment by pcwsmith** [comment]
Styling the entire details/summary element as a button would work in situations where there's only one, but when there are two or more then I'm thinking no to the button idea. Don't want a bunch of buttons stacked together.

BTW I re-read our guidance around buttons in the spec, and it kinda feels like it'd preclude styling the details/summary element in this manner? Basically buttons are intended to encourage the user to click 'em, whereas the details/summary thing is for supplementary, secondary stuff... 

For reference, here's the text of the current spec for the buttons design pattern:

7.24.3 Buttons
Buttons are clickable objects intended to encourage a user to take action.

7.24.3.1 Objective

Use this pattern to:
* execute actions or commands that will change the system state (front or back end), e.g. “Add
comment”, “Submit”, “Send”…

Use when:
* helping a user into or through a transaction (e.g. Feedback)
* invoking functionality (e.g. Share this page)

Do not use when:
* providing a link to another web page (i.e. as navigation)
* providing a link to a downloadable file (e.g. PDF or Excel, etc.)

**Comment by neoinsight** [comment]
@pcwsmith All very good points. It should be used for supplementary secondary stuff that only 20% of people need to see, not 80%. 

The danged thing is people are using it in cases where they NEED to click that one thing - the guidance would suggest the designers should display a button instead. 

So we should focus on making it look clickable for the 20%, not the 80. And you're right, not TOO clickable.  Tricky!

**Comment by thomasgohard** [comment]
The visual treatment I was thinking of was something similar to what they did on the TBS policy suite: http://www.tbs-sct.gc.ca/pol/doc-eng.aspx?id=12453 (which is another example of a use case where the detail/summary should be avoided).

**Comment by neoinsight** [comment]
Yes that looks helpful. You thinking of an icon too like that? Prefer down carets like at top of thread.

**Comment by thomasgohard** [comment]
As I understand it, the icon cannot be modified using CSS. Is that correct @LaurentGoderre?

**Comment by pjackson28** [comment]
@thomasgohard It wouldn't be an issue if you put it on the right like TBS did with the link icon (left for RTL) as you aren't overriding anything (just adding). I didn't see a double down caret in the Glyphicons but there is a single down caret (<code>glyphicon-menu-down</code> http://getbootstrap.com/components/).

**Comment by pjackson28** [comment]
The <code>glyphicon-chevron-down</code> glyphicon could pass as a single down caret as well (it is also what we use for the topic menu).

**Comment by thomasgohard** [comment]
@pjackson28 I think that it will be the icon on the left that matters when the user is scanning the page.

@neoinsight what do you think? Could an additional icon on the right convey clickability?

**Comment by neoinsight** [comment]
Yes, I think that the icon on the right would help convey clickability.

**Comment by thomasgohard** [comment]
Let's try it then. I'll get a pull request ready with the changes.

So I can prioritise, when's the next round of testing?

**Comment by thomasgohard** [comment]
@neoinsight I've added the icon after the label and the box:
![details-visuals](https://cloud.githubusercontent.com/assets/1810242/7327759/bc6c5766-ea9d-11e4-84bf-3aaa4ac8b78c.png)

How's that?

**Comment by pjackson28** [comment]
@thomasgohard What should happen when the labels are different lengths? Should they still be just to the right of text (so out of horizontal alignment) or should they be pushed off further to the right so they can be horizontally aligned?

**Comment by neoinsight** [comment]
Thanks @thomasgohard 

Tricky question @pjackson28 . In the example referred to above at http://www.tbs-sct.gc.ca/pol/doc-eng.aspx?id=12453, the icon is on the far right of the box. But @thomasgohard just passed me a study that seemed to suggest that icons far from words are not beneficial, because people focus on words not icons. 

Remember too that these are used about equally in Canada.ca in lists like this one: http://www.cic.gc.ca/english/citizenship/cit-test.asp  and on their own - like on the Weather page http://weather.gc.ca/. 

@thomasgohard, could you add this format to the details/summary in the test form too? That way we see it in the 'one off' format as well as the list format.

**Comment by thomasgohard** [comment]
The icon is to the right of the text and are not aligned to one another:
![details-visuals-long-label](https://cloud.githubusercontent.com/assets/1810242/7327937/4259d8c0-ea9f-11e4-8c33-1ccab796568a.png)
If the icon was aligned to the right edge of the details/summary, there would be a huge gap of between the label and the icon when the details/summary is wide (like in the screenshot above). Because of that gap, people would be less likely to notice it.

**Comment by neoinsight** [comment]
Oh man, that's so weird in Example 2, where one arrow is pointing down and one is pointing up!
 Funny, didn't notice it earlier. Wow, this is a thorny problem. Am going to go look at the other glyphicons.

**Comment by thomasgohard** [comment]
@neoinsight it does look a bit weird. But it does communicate the action that will be triggered by clicking on it: Down brings down the hidden content under the label; up brings the content up hidding it.

**Comment by thomasgohard** [comment]
@neoinsight the singles and groups all look the same right now. I'll update the test form shortly.

**Comment by neoinsight** [comment]
Hey, Bootstrap shows underlining on hover for their collapse model. http://getbootstrap.com/javascript/#collapse

**Comment by neoinsight** [comment]
Also had wanted the text to be in link color but not underlined except on hover.

**Comment by thomasgohard** [comment]
Right, I forgot the link-like treatment. I'll update the pull request.

**Comment by neoinsight** [comment]
Awesome. Am still worried about the up AND down arrows thing. Maybe we could test both versions. One with box and link-like treatment and no extra icon, and one with same AND the extra icon.

**Comment by thomasgohard** [comment]
OK. So remove the icon for the first round then?

**Comment by neoinsight** [comment]
Yes, ok, thanks!

**Comment by thomasgohard** [comment]
@neoinsight I've updated the test form: http://thomasgohard.github.io/web-form-validation-test/index-en.html.

Is that what you're looking for?

**Comment by neoinsight** [comment]
@thomasgohard Yes, that's terrific - I think that will help a lot. I notice you removed the duplicate underlined version though. You'll remember it was under the one in the last wave of testing as an experimental control  -  basically, if they clicked it instead of the first one, then the first one wasn't quite working as well as we hoped. 

Could you put it back in, just underneath the Browser field itself. Thanks!

**Comment by thomasgohard** [comment]
@neoinsight done.

Let me know if there are further changes you need done.

**Comment by neoinsight** [comment]
There are a few on the form, I'll get them ready. Thanks!

**Comment by nrustand92** [comment]
Any thoughts on this sort of design?
![csb-picture-expandcollapseunderlined-20150506-e](https://cloud.githubusercontent.com/assets/5949078/7502147/d5fa7262-f407-11e4-8730-df5783d06e0b.png)

**Comment by neoinsight** [comment]
@thomasgohard I have analyzed the data from the last round of testing, with the CSS changes for this element. Out of 15 participants who used it, all tried this new version first, rather than trying the underlined version like in the last round of testing. 
I recommend these CSS changes be rolled into the next version of WET or however this would get done, and then we can close this issue. Whew! Thanks for all your help.

**Comment by pcwsmith** [comment]
As discussed yesterday, @thomasgohard and team will port the details/summary CSS from the sample form into WET for release v4.0.16 or v4.0.17. Trying to attach screenshots for ease of reference:
