### ISSUE TITLE
Sign in/Sign out button and My Profile button Dropdown location

### ISSUE THREAD

**Issue by MBlondin** [wet-boew/wet-boew-styleguide#237]
With WET 4.1, where is/will the Sing in/Sign out button and Account settings button located
(image is from WET 3.1)
![image](https://cloud.githubusercontent.com/assets/1737991/5902721/cec22e2e-a54a-11e4-9784-b3eb679c1445.png)

**Comment by neoinsight** [comment]
@thomasgohard had pointed me to this pattern in progress earlier this month: https://github.com/wet-boew/wet-boew/issues/6232

**Comment by MBlondin** [comment]
@neoinsight Thank you Lisa. @thomasgohard is this reference https://github.com/wet-boew/wet-boew/issues/6232 the official Sing in /Sign Out style as of WET 4?

**Comment by RobJohnston** [comment]
This has been done and examples are available for the GCWeb theme:
http://wet-boew.github.io/themes-dist/GCWeb/content-signedon-en.html
http://wet-boew.github.io/themes-dist/GCWeb/content-signedoff-en.html

Close?

**Comment by neoinsight** [comment]
@RobJohnston This looks good!  Am pulling in @dk-tbs to represent the Content and IA spec. One thing I would recommend related to the spec is that the example for the signed-in state should show the recommended Canada.ca state for 'transactional scenarios' as per page 39 of the spec. In particular, that requires removing the Canada.ca menu, the Canada.ca search box, most of the footer and the promo tiles. All of these are not displayed so as not to lead people out of the signed-in transaction state accidentally.

Image from spec for small screen:

![image](https://cloud.githubusercontent.com/assets/1855584/20488285/72e818d4-afd4-11e6-9bdc-803a54a4f9d4.png)

**Comment by DK-TBS** [comment]
Correct!  I should point out though, that although the spec allows for the reduced header/footer etc in transactional scenarios, it doesn't actually demand it.  So it's up to authors/owners to decide whether the transaction is sensitive enough that users should be prevented from accidentally clicking away from the process.  The latest version of the spec describes it like this:

> "On pages where users are engaged in a transactional process—where allowing them to navigate away from the current page would interrupt the intended flow and result in errors, loss of data or accidental termination of the session—elements of the global header and footer may be removed, as follows."

So it's an option, but not strictly mandated.  Up to you to decide whether the errors or loss of data are a real and serious risk  :)

**Comment by RobJohnston** [comment]
I was just trolling for issues that could be closed.  Sounds like this one can be, no?

**Comment by neoinsight** [comment]
Yes thank you!
