### ISSUE TITLE
HELP? - Menu Plugin :: Having an issue on mouseover

### ISSUE THREAD

**Issue by Grim-GH** [wet-boew/wet-boew-styleguide#241]
Background, I'm an accidental WebDev building an internal app. Using newest WET and ASP.

Issue: I have the menu loaded properly, shows the chevron for the sub menu and the menu loads properly when I click the parent object. As soon as I mouse over the child objects in the sub menu it disappears on mouse over.

Sidenote that's probably important: I'm building the menu structure(`<nav><div><ul><li>`) via ASP function/loops from db. Here's the output of the menu once it's presented to the browser...
```asp
<nav role="navigation" id="wb-sm" data-trgt="mb-pnl" class="wb-menu visible-md visible-lg" typeof="SiteNavigationElement">
<div class="pnl-strt container visible-md visible-lg nvbar">
<h2>Menu</h2><div class="row">
<ul class="list-inline menu" role="menubar">
<li><a class="item" href="main_e.asp?user_language=0&bc=init">Home</a></li>
<li>
<a class="item">Sub1</a>
<ul class="sm list-unstyled" id="lore" role="menu">
<li><a class="item" href="page1_e.asp?user_language=0">New Request</a></li>
<li><a class="item" href="page2_e.asp?user_language=0">Existing Requests</a></li>
<li><a class="item" href="log_e.asp?user_language=0">Request Log</a></li>
</ul>
</li>
<li>
<a class="item">Administration</a>
<ul class="sm list-unstyled" id="lore" role="menu">
<li><a class="item" href="profile_e.asp?user_language=0">Profile</a></li>
<li><a class="item" href="staffDetail_e.asp?user_language=0&bc=init">My Staff Info</a></li>
<li><a class="item" href="admin_e.asp?user_language=0&bc=init">Administration</a></li>
</ul>
</li>
<li><a class="item" href="logout_e.asp?user_language=0&bc=init">Log Out</a></li>
</ul></div></nav>
```

The above is all between the `<header>` tags. Can't seem to pinpoint the reason why I lose the menu on mouseover though.

Thanks in advance!

**Comment by LaurentGoderre** [comment]
Few things you should fix. First, you are using the `lore` id twice. The ID needs to be unique for each submenu. Second, the Sub1 and Administration a element need to have an `href` attribute that links to the submenu (the new unique id which replace the `lore` id)

You should also encode the ampersands in your querystring because they cause a syntax error in HTML

**Comment by LaurentGoderre** [comment]
In the future, could you please open support request to the main project repository? https://github.com/wet-boew/wet-boew

**Comment by Grim-GH** [comment]
AH...thanks Laurent. Will go hack at that and add that logic.
As for this thread, sorry about that. Got lost in the links after trying to create my account on Github. Ended up here.

**Comment by LaurentGoderre** [comment]
Absolutely no problem. I was just saying that because you probably can get quicker response there.

**Comment by Grim-GH** [comment]
Continued here: https://github.com/wet-boew/wet-boew/issues/6591

**Comment by Grim-GH** [comment]
Closing this thread
