### ISSUE TITLE
Absolute positioning: First example displayed code is buggy

### ISSUE THREAD

**Issue by KarinLau** [wet-boew/wet-boew-styleguide#244]
Hi,
In http://wet-boew.github.io/wet-boew-styleguide/v4/design/position-en.html the displayed code of the first example is not the same as the example showed. So it doesn't work when copying it and trying on your own.

**Comment by LaurentGoderre** [comment]
@sviens can you take care of this?

**Comment by RobJohnston** [comment]
Seems to be an exact copy now that the style guide has been updated.  Close?
