### ISSUE TITLE
GC Banner does not display correctly. How to correct?

### ISSUE THREAD

**Issue by davidng2580** [wet-boew/wet-boew-styleguide#245]
Hi everyone,

I am new to WET 3.1.
The GC Banner works fine at work. However, at home, it does not render correctly (see Figure 1).
The CSS are loaded as in Figure 2.

Please advise me how to correct this situation.
Many thanks for your help.

Figure 1: GC Banner at home
![image](https://cloud.githubusercontent.com/assets/11884190/7337750/0b7b4b30-ec03-11e4-9da9-8235ed6b273a.png)

Figure 2: Chrome - Resources display loaded CSS
![image](https://cloud.githubusercontent.com/assets/11884190/7337768/7481408a-ec03-11e4-8cef-cacbbd61e734.png)

**Comment by LaurentGoderre** [comment]
Perhaps your server is not serving them right. DO you have a URL we can look at?

**Comment by davidng2580** [comment]
Hi Laurent,

 

Thank you for your tip. There was nested Form tag.

Correction was done & it is working.

 

David
