### ISSUE TITLE
help for dropdown menu

### ISSUE THREAD

**Issue by marieeved** [wet-boew/wet-boew-styleguide#254]
hi,
in the WET, we don't have the code for a dropdown menu. I already read messages on git hub about that, that you will not add such a code... but canada.ca have a dropdown menu. They use an other technique : "data-ajax". I don't know this tag. I tried to use it, I change the path, I made few modifications to the doc : sitemenu-fr.html (with my own labels and links) and it didn't work. Can someone help me with this?

**Comment by LaurentGoderre** [comment]
Can you please close this issue and open it on the main project: https://github.com/wet-boew/wet-boew

**Comment by marieeved** [comment]
sorry. thanks for the info.

**Comment by tommydevdocs** [comment]
Hi, 

I'm getting the same issue. The site is only replacing the AJAX Menu on the homepage. I tried with different paths /,  ~/,  ../.

**Comment by LaurentGoderre** [comment]
In that case it's probably that you should be using absolute paths for all pages
