### ISSUE TITLE
is a div 2 columns in a div 3 columns possible?

### ISSUE THREAD

**Issue by marieeved** [wet-boew/wet-boew-styleguide#255]
hi,
I tried to have a carroussel with text aside. The text is not the text that goes with the carroussel (it's for an other section). I was able to put them seperatly in a "well" and in the principal framework, but I want them bigger. In fact, I want the carousel and text occupy the space of the entire length of the page (in my div), so 1/2 -1/2. but my div is already structured in 3 columns (1 / 3-1 / 3-1 / 3) as canada.ca on How to achieve this? Thanks.

**Comment by LaurentGoderre** [comment]
This should also be filed on the main repo https://github.com/wet-boew/wet-boew. However bootstrap does allow for nested grid cells. When you open the new issue can you also include a diagram that shows what it should look like?

**Comment by marieeved** [comment]
thanks Laurent.
