### ISSUE TITLE
Breadcrumbs and Related Links in style guide broken

### ISSUE THREAD

**Issue by kellerd** [wet-boew/wet-boew-styleguide#266]
Found a lot of Related Links that switch sections in the style guide, or the breadcrumbs in the style guide come up with 404 errors.

Example page: http://wet-boew.github.io/wet-boew-styleguide/v4/design/icons-en.html
 Related link to Accessibility guide is broken, breadcrumbs broken

Other examples of correct and broken links

Link found: http://wet-boew.github.io/wet-boew-styleguide/v4/wet-boew/design/index-en.html
 Should be: http://wet-boew.github.io/wet-boew-styleguide/v4/design/index-en.html

Link found:http://wet-boew.github.io/wet-boew-styleguide/v4/accessibility/design/icons-en.html
 Should be: http://wet-boew.github.io/wet-boew-styleguide/v4/design/icons-en.html

Link found:http://wet-boew.github.io/wet-boew-styleguide/v4/accessibility/images-en.html
 Should be: http://wet-boew.github.io/wet-boew-styleguide/v4/accessibility/requirements/images-en.html

Link found: http://wet-boew.github.io/wet-boew-styleguide/v4/wet-boew/index-en.html
 Should be: http://wet-boew.github.io/wet-boew-styleguide/v4/index-en.html

**Comment by RobJohnston** [comment]
Checked all these... With the re-write of the style guide, most of this has been fixed.  

The only one still broken in this list is the link to the Accessibility guide on http://wet-boew.github.io/wet-boew-styleguide/v4/accessibility/requirements/images-en.html.   The breadcrumb "Style guide" actually links to the accessibility guide.

**Comment by kodecount** [comment]
@RobJohnston If you want I can do up a quick PR to fix this?

**Comment by kodecount** [comment]
@RobJohnston Also should the french link be removed until translation of the accessibility guides are complete (if they are in the works)?

**Comment by RobJohnston** [comment]
Sure... I just had a few minutes free, so went looking issues to close.

**Comment by kodecount** [comment]
I'll see about @cfarquharson input before I continue?

**Comment by cfarquharson** [comment]
I'm not sure who did the accessibility guide.  It wasn't me.  I would be great if it could be reworked and integrated into the guide.  Currently it's in English only and could use some updating.

**Comment by thekodester** [comment]
Closing as fixed by https://github.com/wet-boew/wet-boew-styleguide/issues/363 and https://github.com/wet-boew/wet-boew-styleguide/pull/364.
