### ISSUE TITLE
Breadcrumb links are broken in the documentation 

### ISSUE THREAD

**Issue by masterbee** [wet-boew/wet-boew-styleguide#268]
Breadcrumb links for "Style Guide" and  "Design Guide" are broken in your documentation.
For example see [Buttons Example Page](http://wet-boew.github.io/wet-boew-styleguide/v4/design/buttons-en.html)
And check the breadcrumb link

/cc @jaycuse

**Comment by RobJohnston** [comment]
Dupe of https://github.com/wet-boew/wet-boew-styleguide/issues/266
