### ISSUE TITLE
The title for this page should be Design Guide or something similar to level 1 heading

### ISSUE THREAD

**Issue by dfarough** [wet-boew/wet-boew-styleguide#273]
I noticed this issue when bookmarking the page.  It came up as WET examples or something.

**Comment by dfarough** [comment]
Same issue for the writing guide as well.

**Comment by dfarough** [comment]
The same issue applies to the accessibility guide.

**Comment by thekodester** [comment]
Closing as fixed by https://github.com/wet-boew/wet-boew-styleguide/issues/363 and https://github.com/wet-boew/wet-boew-styleguide/pull/364.
