### ISSUE TITLE
The Absolute Positioning Image Not Showing

### ISSUE THREAD

**Issue by mrryancgeorge** [wet-boew/wet-boew-styleguide#275]
The images under Absolute Positioning are broken links and not displaying.

**Comment by RobJohnston** [comment]
Where is this?  On this page:  http://wet-boew.github.io/wet-boew-styleguide/v4/design/position-en.html?

I don't see the problem.  These link are working for me:  

- http://wet-boew.github.io/wet-boew-styleguide/v4/design/images/position.png
- http://wet-boew.github.io/wet-boew-styleguide/v4/design/images/position-mini-1.png

**Comment by mrryancgeorge** [comment]
It's a minor issue I found here:
http://wet-boew.github.io/wet-boew-styleguide/v4/design/options-en.html

![missing images](https://cloud.githubusercontent.com/assets/20935045/17563796/ca8d0c88-5ee5-11e6-9c13-de1658c8097f.JPG)
