### ISSUE TITLE
Link to Forms Accessibility page invalid

### ISSUE THREAD

**Issue by CalvinRodo** [wet-boew/wet-boew-styleguide#277]
The link to the Form Accessibility Guide provided on the Forms page in the styleguide gives a 404 error: 
Page with link: http://wet-boew.github.io/wet-boew-styleguide/v4/design/forms-en.html
404 error link: http://wet-boew.github.io/wet-boew-styleguide/v4/accessibility/forms-en.html

**Comment by CalvinRodo** [comment]
I imagine this is related to #118

**Comment by RobJohnston** [comment]
And right below that, "Keyboard and user controls" is also broken.  Not sure, but I think that the correct destination are:  

- http://wet-boew.github.io/wet-boew-styleguide/v4/accessibility/requirements/forms-en.html
- http://wet-boew.github.io/wet-boew-styleguide/v4/design/keyboard-en.html

**Comment by CalvinRodo** [comment]
These links no longer exist so I'm happy to close this.
