### ISSUE TITLE
State of development on the StyleGuide

### ISSUE THREAD

**Issue by CalvinRodo** [wet-boew/wet-boew-styleguide#279]
@pjackson28 I'm curious what the state of development on the style guide is? The last commit was on May 6th and before that it was hasn't really had any work on it since summer of last year. Is this project basically abandoned by TB? Are we ever going to have WET be properly documented?

**Comment by pjackson28** [comment]
@CalvinRodo I'm not the lead of WET anymore so I'll need to defer to @masterbee who leads it now or someone from his team.

**Comment by CalvinRodo** [comment]
Sounds good.

**Comment by CalvinRodo** [comment]
@masterbee Any answer for this? 

The following issues from @MaryBethBaker illustrate the need to complete the documentation for WET-BOEW. 
- wet-boew/wet-boew#7647 
- wet-boew/wet-boew#7648
- wet-boew/wet-boew#7649

**Comment by MaximMartel** [comment]
Hi @CalvinRodo,

I will be looking into these issues and update the documentation accordingly this week.

Thank you,

**Comment by MaximMartel** [comment]
First 2 are taken care of, looking into #7649

**Comment by CalvinRodo** [comment]
So does that mean that development will continue on the style guide? I can link a couple of older issues I have opened in the wet-boew issue list so that they can be actioned on if you'd like.

**Comment by MaximMartel** [comment]
Please do @CalvinRodo, I will take a look and action them as soon as I can

**Comment by MaximMartel** [comment]
Please do @CalvinRodo, I will take a look and action them as soon as I can and action appropriately

**Comment by CalvinRodo** [comment]
@MaximMartel  Should new issues regarding the style guide be entered in this repository or tracked in the main wet repo?

**Comment by cfarquharson** [comment]
@CalvinRodo It's been updated, translated and beefed up :)

**Comment by CalvinRodo** [comment]
Cool!
