### ISSUE TITLE
New link for font-awesome

### ISSUE THREAD

**Issue by crochefort** [wet-boew/wet-boew-styleguide#280]
This page : http://wet-boew.github.io/wet-boew-styleguide/v4/design/icons-en.html need to be updated

The link for font-awesome has changed!

This is the new link : https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css

From : https://www.bootstrapcdn.com/fontawesome/

**Comment by MaximMartel** [comment]
Hi @crochefort,

Thanks a lot for this valuable information, i will update the style guide soon reflecting this change.
