### ISSUE TITLE
Form Validation Implementation Example Incorrect

### ISSUE THREAD

**Issue by CalvinRodo** [wet-boew/wet-boew-styleguide#283]
The following line code example is incorrect
```HTML
<label for="fname1">
	<span class="field-name">First Name</span> <strong>(required)</strong>
</label>
````

The strong tag around (required) needs to have the class required added to it otherwise the text (required) is black not red:
```HTML
<label for="fname1">
	<span class="field-name">First Name</span> <strong class="required">(required)</strong>
</label>
````

**Comment by CalvinRodo** [comment]
@MaximMartel

**Comment by MaximMartel** [comment]
Thanks @CalvinRodo !

**Comment by MaximMartel** [comment]
@CalvinRodo 

https://github.com/wet-boew/wet-boew/pull/7661

**Comment by MaximMartel** [comment]
Since wet-boew/wet-boew#7661 has been merged with this fix, closing this issue.
