### ISSUE TITLE
Newest files accidently put in root of master/ instead of in design/ and writing/

### ISSUE THREAD

**Issue by cfarquharson** [wet-boew/wet-boew-styleguide#290]
I accidentally put the new files in the root folder instead of the design/ and writing/ folder.  I have since uploaded them to the correct folders but don't know how to remove the copies from the root folder?

Also, the new files are also in French but because there seems to be no attached French template for Travis to use, it fails the build.  I dont' know how to fix that.  Can someone look into this for me? Sorry about the hassle.

C

**Comment by cfarquharson** [comment]
@LaurentGoderre Can you come by my rescue?

**Comment by cfarquharson** [comment]
@shawnthompson @nschonni Can you help out, per above.  I have merged in the newest content (which is now in both languages).  The problem that I accidentally put the files in the root folder instead of into the design/ and writing/ folders.  I have since put the correct files in those folders BUT I don't know how to delete them out of the root.  ALSO, since there is no French template attached to the style guide, the Travis build fails now that there are french pages.  Can you fix this as it's outside my skill set?

**Comment by cfarquharson** [comment]
@EricDunsworth please see above.  Can you help out?

**Comment by EricDunsworth** [comment]
Done in #294.

@cfarquharson Btw just wondering why you weren't able to make these deletions on your own? If you don't feel comfortable with git command line, I'd highly recommend using a git GUI such as [TortoiseGit](https://tortoisegit.org/). I've been using it for years without any issues.
