### ISSUE TITLE
Remove blue alert box and add images folder

### ISSUE THREAD

**Issue by cfarquharson** [wet-boew/wet-boew-styleguide#295]
I need the blue alert boxes that appear directly below the H1 removed from the build (like on this page: http://wet-boew.github.io/wet-boew-styleguide/v4/design/index-en.html ) That text is already added to the necessary pages (on the right).

I need someone to create an 'images/' folder for me here: `wet-boew.github.io/wet-boew-styleguide/v4/writing/images/` so I can upload some images needed to support the guide

@shawnthompson @LaurentGoderre can you help?

**Comment by duboisp** [comment]
@cfarquharson you only need to clean the HTML in this following file

https://github.com/wet-boew/wet-boew-styleguide/blob/master/site/includes/sitewidemessages.hbs

Cheers

**Comment by cfarquharson** [comment]
@duboisp Thanks!
