### ISSUE TITLE
<def> style in italic is difficult to read for users with dyslexia and other reading disorders 

### ISSUE THREAD

**Issue by RubyDo** [wet-boew/wet-boew-styleguide#335]
Hello, 

Currently <def> in a definition list add an italic styling. dfn {font-style: italic;}

Italic styling is discouraged by the Canada.ca content style guide https://www.canada.ca/en/treasury-board-secretariat/services/government-communications/canada-content-style-guide.html#wp4-2

Recommended fix is to use a strong instead e.g. dfn {font-weight:bold;}

**Comment by cfarquharson** [comment]
@RubyDo the styleguide does not force italics, it's WET4 itself that does this.  Please add your comments to the existing thread on this topic on that repository https://github.com/wet-boew/wet-boew/issues/7631
