### ISSUE TITLE
Update the build setup to follow the rest of the WET repos

### ISSUE THREAD

**Issue by nschonni** [wet-boew/wet-boew-styleguide#352]
Seems like this one has fallen pretty far behind and is failing now

**Comment by thomasgohard** [comment]
This is now causing people to see outdated and incorrect information that has been corrected but not published due to the build being broken: https://github.com/wet-boew/GCWeb/issues/1354.

**Comment by thekodester** [comment]
Closing as fixed by https://github.com/wet-boew/wet-boew-styleguide/issues/363 and https://github.com/wet-boew/wet-boew-styleguide/pull/364.
