### ISSUE TITLE
Adxstudio Portal

### ISSUE THREAD

**Issue by GitRubby** [wet-boew/wet-boew-styleguide#355]
We are going to use Adxstudio Portal as the public front end for our CRM Dynamics application.
Just wondering if there is anyone that has applied the WET template to Adxstudio and would have any documentation to share.  (Or link to a website, or suggestion as to where I should be asking this question).

Thanks.

**Comment by shawnthompson** [comment]
Opening an issue in the wet-boew repo might be better. This repo doesn't get much love these days.

https://github.com/wet-boew/wet-boew/issues
