### ISSUE TITLE
"Users do scroll down the page" - Update

### ISSUE THREAD

**Issue by mgifford** [wet-boew/wet-boew-styleguide#359]
Dates on some of these quotes are relevant. This quote was from a study that was written about in 2010.  User behaviors change over time:

"Web users spend 80% of their time looking at information above the page fold. Although users do scroll, they allocate only 20% of their attention below the fold."

https://www.nngroup.com/articles/scrolling-and-attention-original-research/

With mobile devices and infinite scroll, I do think that these ideas are a bit outdated.  

Would love to have someone confirm this who knows UX better than I do.

**Comment by RobJohnston** [comment]
I guess that's in reference to these two pages:
* http://wet-boew.github.io/wet-boew-styleguide/v4/design/pagination-en.html#supporting
* http://wet-boew.github.io/wet-boew-styleguide/v4/writing/rchtctr-en.html#length

**Comment by mgifford** [comment]
Sorry..  Dates I do think are useful on some quotes..  But I think that that I totally misread what was on the printed screen.  

Anyways, yes.  It was in reference to that @RobJohnston - feel free to re-open it but given my misreading I'm going to close it now.
