### ISSUE TITLE
New Style Guide?

### ISSUE THREAD

**Issue by thekodester** [wet-boew/wet-boew-styleguide#363]
So I was clean up my emails notice a few open issues for this repo. When looking into a few of them this repo is very broken. Things I noticed:

- Does not pull the latest CSS/JS (still using WET 4.0.29 from 2018)
- Menus and Breadcrumbs are broken
- Lots of broken HTML, like `<title>` tags are incomplete
- Does not use proper i18n
- _design-templates_ and _old_ folder seem out of place in this repo

I'm having a hard time understanding .gitmodules, .travis.yml, Gruntfile.coffee, package-lock.json, package.json and where they are collecting and generating some of the HTML content. I believe it the wet-boew-dist repo, but unsure.

@duboisp Thoughts?

**Comment by duboisp** [comment]
The main issue is the build script on that repository is currently broken essentially because it's not compatible with the recent version of nodejs.

Using a build script that require nodejs might over complicate the goal of this repository. 

Do you have any proposal on how we can better manage this style guide? May be by using a jekyll template like I did for the wet-boew-documentation website? 

What do you think?

**Comment by thekodester** [comment]
Jekyll would defiantly simplify the repo and make it easier to fix some of the issues (or do updates in future).

**Comment by duboisp** [comment]
Do you want to try to do that conversion? 

The biggest job would be to migrate the handlebar (.hbs) into a markdown (.md) equivalent files.
And for the example that require custom markup would require to use the jekyll escape like 

```
{::nomarkdown}
{% raw %}
...HTML code here...
{% endraw %} {:/}
```

**Comment by thekodester** [comment]
I don't mind.

Would we also need to pull over the following:
- _includes
- _layouts
- assets
- .editiorconfig
- .gitattributes
- .gitignore
- _config.yml
- params.json

From wet-boew-documentation repo?

**Comment by duboisp** [comment]
ok, do what need to be done.

For topic where it's make sense, feel free to link back to section in the https://design.gccollab.ca/ . I know in the future, there is a moderated risk to have both project being aligned.

**Comment by thekodester** [comment]
@duboisp I don't have the ability, but the link on main page:

FROM (http://wet-boew.github.io/wet-boew-styleguide/v4/index-en.html):
![Screen Shot 2019-04-11 at 9 12 12 AM](https://user-images.githubusercontent.com/23484460/55960010-ef592980-5c39-11e9-98ab-6d5ba8fce9fc.png)

TO:
http://wet-boew.github.io/wet-boew-styleguide/index-en.html

**Comment by thekodester** [comment]
I'll also do some testing and see if any links are incorrect, since I was testing on a localhost it quite possible.

**Comment by duboisp** [comment]
I am sending a PR that will fix that in a minutes

**Comment by duboisp** [comment]
see #367

**Comment by thekodester** [comment]
Also this update appears to address the following issues:
#142/#220
#266
#273
#352

**Comment by duboisp** [comment]
You should be able to merge my PR  and close those issue.

**Comment by thekodester** [comment]
Your PRs are merged, I also submitted one to fix different issues. Should I merge it?

**Comment by thekodester** [comment]
Nevermind internet slow lately, see it merged, closing issue and the other ones.

**Comment by thekodester** [comment]
Closing as fixed by https://github.com/wet-boew/wet-boew-styleguide/pull/364, https://github.com/wet-boew/wet-boew-styleguide/pull/365, https://github.com/wet-boew/wet-boew-styleguide/pull/366, and https://github.com/wet-boew/wet-boew-styleguide/pull/367.
