### ISSUE TITLE
Accessibility Guide

### ISSUE THREAD

**Issue by thekodester** [wet-boew/wet-boew-styleguide#369]
Unsure if it was intentional since it appears to be only English at this time, but the [Accessibility Guide](https://wet-boew.github.io/wet-boew-styleguide/accessibility/index-en.html) has no link anywhere (this repo or even the main repo).

**Comment by duboisp** [comment]
I don't think that was intentional, feel free to add it

**Comment by thekodester** [comment]
Closing as resolved by #370.
