### ISSUE TITLE
Dead Links

### ISSUE THREAD

**Issue by thekodester** [wet-boew/wet-boew-styleguide#381]
Need to work on finding dead/outdated links and updating.

List of links (found so far):
- https://getbootstrap.com/ too https://getbootstrap.com/docs/3.3/
- https://bootstrapdocs.com/v3.3.1/docs/components/#glyphicons too https://getbootstrap.com/docs/3.3/components/#glyphicons

This was discussed a little in https://github.com/wet-boew/wet-boew-styleguide/pull/380 and there a some related issues (one still open is https://github.com/wet-boew/wet-boew-styleguide/issues/118).

**Comment by thekodester** [comment]
Mostly resolved by https://github.com/wet-boew/wet-boew-styleguide/pull/384.

**Comment by GormFrank** [comment]
Can this issue be closed or is it an ongoing one?

**Comment by thekodester** [comment]
I can close it.

**Comment by GormFrank** [comment]
Wow that was quick. Thanks!
