### ISSUE TITLE
WET4.0 Modal Overlay mask div background color 

### ISSUE THREAD

**Issue by Lynntaohan** [wet-boew/wet-boew-styleguide#406]
I use WET4.0 Centered popup -Modal (lightbox Modal) to create a modal, but I cannot change the mask background color from black to gray, and made it opacity 0.5 (filer 50). 
I tried to update theme.css, theme.min.css mfp-hide, modal-dialog, modal-content, overlay-def, overly-lg, modal-body class, but nothing changed, the background was still black and it is not transparent. 
![lightbox](https://user-images.githubusercontent.com/38365516/163593108-a664fa8c-3aef-4ee4-9f3d-498b2d7c4ed3.jpg)

**Comment by kodz1** [comment]
To change the background try:
```
.mfp-bg {
background: #808080 !important;
opacity: 0.49 !important;
}
```

If you want to see the page contents, try also:
```
body.wb-modal summary, body.wb-modal>#wb-tphp, body.wb-modal>footer, body.wb-modal>header, body.wb-modal>main {
visibility: visible !important;
}
```
